version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-app-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tta5sut6sgsx"
s3_prefix = "my-app-backend"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
