AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - AppSync to DynamoDB

Resources:
  # Define a DynamoDB table
  CustomerFeedbackTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  # AppSync Role
  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
      Policies:
        - PolicyName: DDBAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt CustomerFeedbackTable.Arn

  # AppSync API - The GraphQL API for the Notes App
  AppSyncApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: FeedbackApi
      XrayEnabled: true
      AuthenticationType: API_KEY

  # API Key for external access
  AppSyncApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId

  # AppSync Schema
  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Definition: |
        type Feedback {
          id: ID!
          rating: Int
          reason: String
        }
        type PaginatedFeedback {
          feedback: [Feedback!]!
          nextToken: String
        }
        type Query {
          getAllFeedback(limit: Int, nextToken: String): PaginatedFeedback!
          getFeedback(id: ID!): Feedback
        }
        type Mutation {
          saveFeedback(id: ID!, rating: Int!, reason: String!): Feedback
          deleteFeedback(id: ID!): Feedback
        }
        type Schema {
          query: Query
          mutation: Mutation
        }

  # AppSync Data Source for DynamoDB
  AppSyncCustomerFeedbackDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: CustomerFeedbackDataSource
      ApiId: !GetAtt AppSyncApi.ApiId
      Description: "The Customer Feedback Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt DynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref CustomerFeedbackTable
        AwsRegion: !Sub ${AWS::Region}

  # Resolver: Query - Get All Feedback
  AppSyncGetAllFeedbackQueryResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getAllFeedback
      DataSourceName: !GetAtt AppSyncCustomerFeedbackDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Scan",
          "limit": $util.defaultIfNull(${ctx.args.limit},20),
          "nextToken": $util.toJson(${ctx.args.nextToken})
        }
      ResponseMappingTemplate: |
        {
          "feedback": $util.toJson($ctx.result.items),
          "nextToken": $util.toJson(${ctx.args.nextToken})
        }

  # Resolver: Query - get one Feedback record
  AppSyncGetFeedbackQueryResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getFeedback
      DataSourceName: !GetAtt AppSyncCustomerFeedbackDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "GetItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  # Resolver: Mutation - Save Feedback
  AppSyncSaveFeedbackMutationResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: saveFeedback
      DataSourceName: !GetAtt AppSyncCustomerFeedbackDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "PutItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          },
          "attributeValues": {
            "rating": $util.dynamodb.toDynamoDBJson($ctx.args.rating),
            "reason": $util.dynamodb.toDynamoDBJson($ctx.args.reason)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  # Resolver: Mutations - Delete note
  AppSyncDeleteFeedbackMutationResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteFeedback
      DataSourceName: !GetAtt AppSyncCustomerFeedbackDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "DeleteItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

Outputs:
  GraphQLApiEndpoint:
    Description: The URL to the GraphQL Endpoint
    Value: !GetAtt AppSyncApi.GraphQLUrl
  APIKey:
    Description: API Key for using the GraphQL endpoint. (header key name 'x-api-key')
    Value: !GetAtt AppSyncApiKey.ApiKey
